server:
  port: 8081
  servlet:
    session:
      timeout: 60s
spring:
  mvc:
    async:
      request-timeout: 20000
  #mybatis链接数据库相关配置
  datasource:
    url: jdbc:mysql://121.40.225.244/oneMonthLearning?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver